id: PD34FADF1
initial_creation_type: input
source_metadata:
  title: Avalokiteśvara Series
  language: pt
  description: 'A series of texts related to the bodhisattva of compassion, Avalokiteśvara
    (spyan ras gzigs):'
  volume:
    2adc25f4072849b78b7a546b330090df:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Dukngal Rangdrol
    4c109ca4209e464b8d24d48371885007:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Dukngal Rangdrol
    514613c9436f49acb9abd9aced7c1e57:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dukngal Rangdrol
    cf3b61426baf4a6492a2cb22bf08d158:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Dukngal Rangdrol
    016d10eeb19045238529a8e2263e507f:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Dukngal Rangdrol
    e2d5c82e97bc4b17bd8f25e2d48aaa3d:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Dukngal Rangdrol
    ccc7b9b2adee41d88ae9331acc270936:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Dukngal Rangdrol
    42ef72b9df2647b9b971548602c9da36:
      title: Praise of Noble Avalokiteśvara
      parent: Praise
    31759c9f355d41c88e6f2549776f2030:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Praise
    517eb49c2f464be7b351275d2a6e8855:
      title: Prayer to Avalokiteśvara
      parent: Prayers
    2443c98d82634310b9e9301a2fdabbf8:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Prayers
    11528cece15044308eea16f1988758d9:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Prayers
    62300737db1a4164a3c074c3e2c71590:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Sādhanas
    4ceb8ccf1af14435a9a47118a06dfc8d:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
    309f231d22544b86bde00f06150a07f4:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    1ed83609fc4143d688bf39e3bd36fc17:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
    170b12284d354762a8ee8839160d05e6:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      parent: Sādhanas
    d53bad64fec5454087cd4e3ec88a4dd0:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Sādhanas
created_at: '2022-03-01T02:54:02.522789'
last_modified_at: '2022-03-01T02:54:02.522791'
